### ISSUE TITLE
[JS:external:...] results to 404

### ISSUE THREAD

**Issue by dongido001** [quantacms/quanta#168]
When you do something like

```
[JS|external:/assets/js/script.js]
```
It returns the document root path like:

```
<script src="/var/www/html/quanta/sites/quanta.test//assets/js/script.js"></script>
```
Instead of 

```
<script src="/assets/js/script.js"></script>
```

Possible line of [code](https://github.com/quantacms/quanta/blob/master/engine/modules/core/page/page.qtags.inc#L86)

**Comment by Aldus83** [comment]
Hey @dongido001 
what if you try with "inline" instead of  "external"? 
[JS|inline:/assets/js/script.js] 

As the external attribute seems only supported by the qtag_CSS 

If it doesn't work, keep the <script src="/assets/js/script.js"></script>, and I'll have a look. 

Thanks for the good catch

**Comment by dongido001** [comment]
Yes the inline worked!
