### ISSUE TITLE
Fix output icons for OPERATIONS qtag

### ISSUE THREAD

**Issue by dariokf** [quantacms/quanta#170]
The OPERATIONS qtag renders in sequence;
- ADD qtag
- EDIT qtag
- DELETE qtag

Currently only ADD qtag create a correct output -> a &oplus; icon.
The other 2 tags renders as the ADD qtag icon code, "&amp;oplus;", instead of edit and delete icon.

I think that it deals also with filter_xss function...

**Comment by Aldus83** [comment]
Hi @dariokf ,
https://github.com/quantacms/quanta/pull/175
This fixes it. I don't like the solution, but now we are passing the attributes by reference, and we can't really reuse the $attributes array in such cases.

I would rather get rid of OPERATIONS altogether...
