### ISSUE TITLE
A way to span qtags into multiple rows.

### ISSUE THREAD

**Issue by dongido001** [quantacms/quanta#172]
Is there a way to span tags into multiple rows? I'm not sure if it's currently available. I tried but the tags were not rendered.

At times your qtags might become very lengthy. It would be nice to span it into multiple lines for readability sake.

An example:

```
[MENU|links={LINK|title=about:about}---{LINK|title=work:work}---{LINK|title=services:services}---{LINK|title=partners:partners}---{LINK|title=blog:blog}---{LINK|title=contact:contact}|menu_class=menu text-center...]
```
Into something like:
```   
 [MENU
       |links={LINK|title=about:about}---{LINK|title=work:work}---{LINK|title=services:services}---{LINK|title=partners:partners}---{LINK|title=blog:blog}---{LINK|title=contact:contact}
       |menu_class=menu text-center...
    ]
```
Or:
```
    [MENU
      |links=
        {LINK|title=about:about}---
        {LINK|title=work:work}---
        {LINK|title=services:services}---
        {LINK|title=partners:partners}---
        {LINK|title=blog:blog}---
        {LINK|title=contact:contact}
      |menu_class=menu text-center...
    ]
```

**Comment by Aldus83** [comment]
Hello @dongido001 ,
allowing spanning to multiple row is a nice idea. I will take care of it personally.
Please note that in your specific example (qtag_MENU) you might use the node mode, aka creating a new node (i.e. top_menu) and inside its tpl.html placing one link per line without separator

{LINK|title=about:about}
{LINK|title=work:work}
{LINK|title=services:services}
{LINK|title=partners:partners}
{LINK|title=blog:blog}
{LINK|title=contact:contact}

then using the node as a target of qtag_MENU, i.e.
[MENU:top_menu]

**Comment by Aldus83** [comment]
@dongido001,
as a first solution, this seems to work:
https://github.com/quantacms/quanta/pull/173

I will not merge it yet, as I am not sure that completely removing newlines is always a good idea. Thinking in example about  PRE  tags, where newlines are actually used.
So it might be better to have it parsed in the real qtags regex:
https://github.com/quantacms/quanta/blob/master/engine/modules/core/qtags/qtags.api.inc#L37

What do you think? Any hints?

**Comment by dongido001** [comment]
Yeah, I think it's more appropriate passing the regex to fetch the tag for the same reason you stated.

I also like the TODO if implemented for advance nesting

**Comment by Aldus83** [comment]
https://github.com/quantacms/quanta/tree/quanta-4.0

The new (Full OO) version of Quanta allows: 
1) Nested Qtags with same delimiters
2) Nested Qtags on multiple lines
i.e. 

[LINK|title=
  [STRING:hello...]
  [STRING:...world] 
:hello]
