### ISSUE TITLE
404 - Github community link in quantacms.com

### ISSUE THREAD

**Issue by pierDipi** [quantacms/quanta#178]
**Step to reproduce**

- Go to [https://www.quantacms.com/](url)

- Go to the bottom of the page, in the footer,  click on the link _**Github community**_.

**Response**

404 - File not found

**Comment by Aldus83** [comment]
Thank you for reporting @pierDipi 
That's fixed now, for the site. 
I'll open another issue for a bug in the [LINK] qtag when including protocol in the link target.
